/* ANNLETRAVEL - SHARED PUBLIC HEADER / FOOTER */
(function () {
    "use strict";
    if (window.location.pathname.includes("/admin/")) return;
    if (!document.querySelector('link[href*="css/i18n.css"]')) { const s=document.createElement("link"); s.rel="stylesheet"; s.href="css/i18n.css"; document.head.appendChild(s); }
    if (!document.querySelector('link[href*="css/audience.css"]')) { const s=document.createElement("link"); s.rel="stylesheet"; s.href="css/audience.css"; document.head.appendChild(s); }
    if (!document.querySelector('link[href*="css/audience-pages.css"]')) { const s=document.createElement("link"); s.rel="stylesheet"; s.href="css/audience-pages.css"; document.head.appendChild(s); }
    const file=(window.location.pathname.split("/").pop()||"index.html").toLowerCase();
    const isBusiness=file==="business.html"||document.body.classList.contains("business-page");
    const active=key=>({home:isBusiness?file==="business.html":file==="ca-nhan.html",tours:!isBusiness&&(file==="tours.html"||file==="tour-detail.html"),destinations:file==="destinations.html"||file==="destination.html",services:!isBusiness&&["services.html","service-detail.html","tickets.html","ticket-detail.html"].includes(file),business:file==="business.html",about:file==="about.html"}[key]?"active":"");
    const destinationMenu=`<div class="nav-dropdown"><a href="destinations.html" class="${active("destinations")}" data-i18n="nav.destinations">Điểm đến <span class="nav-chevron">▾</span></a><ul id="destinationMenu" class="dropdown-menu"></ul></div>`;
    const serviceMenu=`<div class="nav-dropdown"><a href="services.html" class="${active("services")}" data-i18n="nav.services">Dịch vụ <span class="nav-chevron">▾</span></a><ul class="dropdown-menu service-menu"><li><a href="services.html?category=flights">✈️ Vé máy bay</a></li><li><a href="services.html?category=hotels">🏨 Khách sạn</a></li><li><a href="services.html?category=visa">🛂 Visa</a></li><li><a href="services.html?category=passport">🪪 Hộ chiếu</a></li><li><a href="tickets.html">🎫 Vé vui chơi &amp; tham quan</a></li><li><a href="services.html?category=transport">🚗 Xe đưa đón</a></li><li><a href="services.html?category=trains">🚆 Vé tàu</a></li><li><a href="services.html?category=insurance">🛡️ Bảo hiểm du lịch</a></li></ul></div>`;
    const header=document.querySelector("header.header");
    if(header){
        const homeHref=isBusiness?"business.html":"ca-nhan.html",contactHref=isBusiness?"business.html#businessContact":"ca-nhan.html#contact",switchHref=isBusiness?"ca-nhan.html":"business.html",switchLabel=isBusiness?"Cá nhân":"Doanh nghiệp";
        const menu=isBusiness
            ? `<a href="business.html" class="${active("home")}">Trang chủ</a><a href="business.html#businessServices">Giải pháp</a>${destinationMenu}<a href="business.html#businessProcess">Quy trình</a><a href="about.html" class="${active("about")}">Về chúng tôi</a><a href="${contactHref}">Tư vấn</a>`
            : `<a href="${homeHref}" class="${active("home")}" data-i18n="nav.home">Trang chủ</a><a href="tours.html" class="${active("tours")}" data-i18n="nav.tours">Tour</a>${destinationMenu}${serviceMenu}<a href="business.html" class="${active("business")}" data-i18n="nav.business">Doanh nghiệp</a><a href="about.html" class="${active("about")}" data-i18n="nav.about">Về chúng tôi</a><a href="${contactHref}" data-i18n="nav.contact">Liên hệ</a>`;
        header.className=`header audience-header ${isBusiness?"business-shared-header":"personal-shared-header"}`;
        header.innerHTML=`<div class="container header-container"><a href="${homeHref}" class="logo"><img src="images/logo.png" alt="ANNLETRAVEL"></a><nav class="menu">${menu}</nav><div class="public-header-actions"><div class="language-switcher" aria-label="Language selector"></div><a href="${switchHref}" class="audience-switch-btn">${switchLabel}</a><a href="${contactHref}" class="btn btn-header" data-i18n="nav.consult">Tư vấn ngay</a></div></div>`;
    }
    const footer=document.querySelector("footer");
    if(footer){footer.innerHTML=`<div class="container footer-container"><div><a href="${isBusiness?"business.html":"ca-nhan.html"}" class="footer-logo-link"><img src="images/logo.png" class="footer-logo-image" alt="ANNLETRAVEL"></a><p>CÔNG TY TNHH DỊCH VỤ VÀ DU LỊCH ANN LÊ.</p></div><div><h4>Khám phá</h4><a href="${isBusiness?"business.html#businessServices":"tours.html"}">${isBusiness?"Giải pháp doanh nghiệp":"Tất cả tour"}</a><a href="destinations.html">Điểm đến</a><a href="${isBusiness?"business.html":"services.html"}">${isBusiness?"Trang doanh nghiệp":"Dịch vụ"}</a><a href="about.html">Về chúng tôi</a></div><div><h4>Liên hệ</h4><p>Hotline: 0862421655</p><p>Email: dulichannle@gmail.com</p><p>Số 136 phố Hàng Bạc, Phường Hoàn Kiếm, Thành phố Hà Nội</p></div></div><div class="copyright">© 2026 ANNLETRAVEL. All rights reserved.</div>`;}
    const style=document.createElement("style");style.textContent=`.audience-header{position:absolute;top:0;left:0;right:0;z-index:100}.audience-header .header-container{min-height:88px;gap:20px}.audience-header .logo{flex-shrink:0}.audience-header .logo img{width:72px;height:72px;object-fit:contain;display:block}.audience-header .menu>a.active,.audience-header .menu .nav-dropdown>a.active{color:#fff;background:rgba(255,255,255,.12)}.audience-header .menu>a.active::after,.audience-header .menu .nav-dropdown>a.active::after{transform:scaleX(1)}.audience-header .nav-chevron{font-size:10px;margin-left:5px;opacity:.75}.public-header-actions{display:flex;align-items:center;gap:9px;flex-shrink:0}.audience-header .language-switcher{display:flex;align-items:center}.audience-header .audience-switch-btn{display:inline-flex;align-items:center;justify-content:center;min-width:104px;padding:10px 15px;border-radius:999px;background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.32);color:#fff;font-size:12px;font-weight:800;white-space:nowrap;transition:.2s ease}.audience-header .audience-switch-btn:hover{background:#fff;color:var(--primary);transform:translateY(-2px)}.audience-header .btn-header{display:inline-flex!important;padding:10px 16px!important}.business-shared-header .audience-switch-btn{background:#eaf7fd;color:#005B8F;border-color:#eaf7fd}.business-shared-header .audience-switch-btn:hover{background:#fff;color:#0077B6}.business-page .business-switch{display:none!important}.footer-logo-link{display:inline-flex;align-items:center;margin-bottom:10px}.footer-logo-image{width:74px;height:74px;object-fit:contain;display:block}.footer-container>div:nth-child(2) a{display:block;margin:5px 0;color:rgba(255,255,255,.68);font-size:14px}@media(max-width:1100px){.audience-header .menu>a,.audience-header .menu>.nav-dropdown>a{padding:0 8px;font-size:11px}.public-header-actions{gap:5px}.audience-header .audience-switch-btn{min-width:auto;padding:9px 11px}.audience-header .btn-header{padding:9px 12px!important}}@media(max-width:820px){.public-header-actions .audience-switch-btn{display:none}.audience-header .header-container{flex-wrap:wrap}.audience-header .menu{order:3;width:100%;justify-content:flex-start;overflow-x:auto;padding-bottom:5px;scrollbar-width:none}.audience-header .menu::-webkit-scrollbar{display:none}.audience-header .menu>a,.audience-header .menu>.nav-dropdown>a{font-size:13px;min-height:40px;flex-shrink:0}.audience-header .btn-header{display:none!important}.audience-header .language-switcher{order:2}}@media(max-width:650px){.audience-header .header-container{min-height:76px;padding:8px 0}.audience-header .logo img{width:58px;height:58px}.audience-header .menu{gap:8px}.audience-header .menu>a,.audience-header .menu>.nav-dropdown>a{font-size:13px;padding:0 8px}.audience-header .language-switcher{display:none}.footer-logo-image{width:62px;height:62px}}`;document.head.appendChild(style);
    if(typeof window.renderDestinationMenu==="function") window.renderDestinationMenu();
})();
