// ANNLETRAVEL - TICKETS / THINGS TO DO
const ticketState={brands:[],locations:[],tickets:[],brand:'ALL',destination:'ALL',type:'ALL',search:''};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const imgUrl=v=>{const u=String(v||'').trim();return /^https:\/\/[^\s"'<>]+$/i.test(u)?u:'';};
const price=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?`${new Intl.NumberFormat('vi-VN').format(n)} đ`:'Liên hệ';};
const typeLabel=t=>({amusement:'Công viên & khu vui chơi',attraction:'Điểm tham quan',show:'Show & biểu diễn',experience:'Trải nghiệm'})[t]||'Vé vui chơi & tham quan';
const typeIcon=t=>({amusement:'🎢',attraction:'🏛️',show:'🎭',experience:'✨'})[t]||'🎫';
async function loadTickets(){const [b,l,t]=await Promise.all([supabaseClient.from('ticket_brands').select('*').order('sort_order'),supabaseClient.from('ticket_locations').select('*').order('sort_order'),supabaseClient.from('tickets').select('*').order('sort_order')]);if(b.error||l.error||t.error){console.error(b.error||l.error||t.error);const g=document.getElementById('ticketGrid');if(g)g.innerHTML='<div class="ticket-empty">Không thể tải danh sách vé.</div>';return;}ticketState.brands=b.data||[];ticketState.locations=l.data||[];ticketState.tickets=t.data||[];renderFilters();bindFilters();renderTickets();}
function renderFilters(){const f=document.getElementById('ticketFilters');if(!f)return;const dest=[...new Set(ticketState.locations.map(x=>x.destination).filter(Boolean))];const types=[['ALL','Tất cả'],['amusement','Công viên & khu vui chơi'],['attraction','Điểm tham quan'],['show','Show & biểu diễn'],['experience','Trải nghiệm']];f.innerHTML=`<div class="ticket-filter-row"><label>Tìm kiếm<input id="ticketSearch" type="search" placeholder="Tên vé, địa điểm..." value="${esc(ticketState.search)}"></label><label>Thương hiệu<select id="ticketBrand"><option value="ALL">Tất cả thương hiệu</option>${ticketState.brands.map(x=>`<option value="${esc(x.id)}" ${ticketState.brand===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Điểm đến<select id="ticketDestination"><option value="ALL">Tất cả điểm đến</option>${dest.map(x=>`<option value="${esc(x)}" ${ticketState.destination===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label></div><div class="ticket-type-row">${types.map(([v,n])=>`<button type="button" class="ticket-filter ${ticketState.type===v?'active':''}" data-type="${v}">${n}</button>`).join('')}</div><button type="button" id="ticketReset" class="ticket-clear">Xóa bộ lọc</button>`;}
function bindFilters(){document.getElementById('ticketSearch')?.addEventListener('input',e=>{ticketState.search=e.target.value;renderTickets();});document.getElementById('ticketBrand')?.addEventListener('change',e=>{ticketState.brand=e.target.value;renderTickets();});document.getElementById('ticketDestination')?.addEventListener('change',e=>{ticketState.destination=e.target.value;renderTickets();});document.querySelectorAll('.ticket-filter').forEach(b=>b.addEventListener('click',()=>{ticketState.type=b.dataset.type;renderFilters();bindFilters();renderTickets();}));document.getElementById('ticketReset')?.addEventListener('click',()=>{Object.assign(ticketState,{brand:'ALL',destination:'ALL',type:'ALL',search:''});renderFilters();bindFilters();renderTickets();});}
function filtered(){const q=ticketState.search.trim().toLowerCase();return ticketState.tickets.filter(t=>{const l=ticketState.locations.find(x=>x.id===t.location_id);return (ticketState.brand==='ALL'||l?.brand_id===ticketState.brand)&&(ticketState.destination==='ALL'||l?.destination===ticketState.destination)&&(ticketState.type==='ALL'||t.ticket_type===ticketState.type)&&(!q||`${t.name} ${t.short} ${l?.name||''} ${l?.destination||''}`.toLowerCase().includes(q));});}
function renderTickets(){const g=document.getElementById('ticketGrid'),c=document.getElementById('ticketCount');if(!g)return;const list=filtered();if(c)c.textContent=`${list.length} lựa chọn`;if(!list.length){g.innerHTML='<div class="ticket-empty">Không có vé phù hợp. Hãy thử thay đổi bộ lọc.</div>';return;}g.innerHTML=list.map(t=>{const l=ticketState.locations.find(x=>x.id===t.location_id),b=ticketState.brands.find(x=>x.id===l?.brand_id),image=imgUrl(t.image)||imgUrl(l?.image),name=esc(t.name);return `<article class="ticket-card"><div class="ticket-media">${image?`<img src="${esc(image)}" alt="${name}" loading="lazy">`:`<span>${typeIcon(t.ticket_type)}</span>`}<span class="ticket-badge">${esc(typeLabel(t.ticket_type))}</span></div><div class="ticket-body"><div class="ticket-brand">${esc(b?.name||'')}</div><div class="ticket-location">📍 ${esc(l?.name||'')} · ${esc(l?.destination||'')}</div><h3>${name}</h3><p>${esc(t.short)}</p><div class="ticket-card-footer"><div class="ticket-price">Từ<strong>${price(t.price_from)}</strong></div><a class="btn btn-primary" href="ticket-detail.html?slug=${encodeURIComponent(t.slug)}">Xem vé</a></div></div></article>`;}).join('');}
document.addEventListener('DOMContentLoaded',loadTickets);
