// ANNLETRAVEL - TICKETS / THINGS TO DO
function escapeTicketHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function ticketImageUrl(value){const url=String(value||'').trim();return /^https:\/\/[^\s"'<>]+$/i.test(url)?url:'';}
function ticketType(service){const type=String(service.service_type||'').toLowerCase();if(type==='amusement')return 'Công viên & khu vui chơi';if(type==='show')return 'Show & biểu diễn';if(type==='attraction')return 'Điểm tham quan';return 'Trải nghiệm';}
function ticketLocation(service){return String(service.destination||'Theo điểm đến').trim()||'Theo điểm đến';}
function ticketIcon(service){const type=ticketType(service);if(type==='Công viên & khu vui chơi')return '🎢';if(type==='Show & biểu diễn')return '🎭';if(type==='Điểm tham quan')return '🏛️';return '✨';}
function formatTicketPrice(value){const n=Number(value);return Number.isFinite(n)&&n>0?`${new Intl.NumberFormat('vi-VN').format(n)} đ`:'Liên hệ';}
let ticketServices=[];let activeTicketType='ALL';let ticketSearch='';let ticketDestination='ALL';let ticketPrice='ALL';
async function loadTickets(){const {data,error}=await supabaseClient.from('services').select('*').eq('category_id','tickets').eq('active',true).order('sort_order',{ascending:true});if(error){console.error('Load tickets error:',error);renderTicketError();return;}ticketServices=data||[];renderTicketDestinations();renderTicketFilters();bindTicketControls();renderTickets();}
function renderTicketError(){const grid=document.getElementById('ticketGrid');if(grid)grid.innerHTML='<div class="ticket-empty">Không thể tải danh sách vé. Vui lòng thử lại sau.</div>';}
function renderTicketDestinations(){const el=document.getElementById('ticketDestination');if(!el)return;const destinations=[...new Set(ticketServices.map(s=>ticketLocation(s)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi'));el.innerHTML='<option value="ALL">Tất cả điểm đến</option>'+destinations.map(d=>`<option value="${escapeTicketHtml(d)}">${escapeTicketHtml(d)}</option>`).join('');el.value=ticketDestination;}
function renderTicketFilters(){const el=document.getElementById('ticketFilters');if(!el)return;const types=['ALL','Công viên & khu vui chơi','Điểm tham quan','Show & biểu diễn','Trải nghiệm'];el.innerHTML=types.map(type=>`<button class="ticket-filter${activeTicketType===type?' active':''}" data-type="${escapeTicketHtml(type)}">${type==='ALL'?'Tất cả':escapeTicketHtml(type)}</button>`).join('');el.querySelectorAll('.ticket-filter').forEach(btn=>btn.addEventListener('click',()=>{activeTicketType=btn.dataset.type;renderTicketFilters();renderTickets();}));}
function bindTicketControls(){const search=document.getElementById('ticketSearch');const destination=document.getElementById('ticketDestination');const price=document.getElementById('ticketPrice');const reset=document.getElementById('ticketReset');if(search)search.addEventListener('input',()=>{ticketSearch=search.value.trim().toLowerCase();renderTickets();});if(destination)destination.addEventListener('change',()=>{ticketDestination=destination.value;renderTickets();});if(price)price.addEventListener('change',()=>{ticketPrice=price.value;renderTickets();});if(reset)reset.addEventListener('click',()=>{ticketSearch='';ticketDestination='ALL';ticketPrice='ALL';activeTicketType='ALL';if(search)search.value='';if(destination)destination.value='ALL';if(price)price.value='ALL';renderTicketFilters();renderTickets();});}
function matchesTicketPrice(service){const n=Number(service.price_from);if(ticketPrice==='ALL')return true;if(ticketPrice==='contact')return !(Number.isFinite(n)&&n>0);if(!(Number.isFinite(n)&&n>0))return false;if(ticketPrice==='under500')return n<500000;if(ticketPrice==='500to1000')return n>=500000&&n<=1000000;if(ticketPrice==='over1000')return n>1000000;return true;}
function renderTickets(){const grid=document.getElementById('ticketGrid');const count=document.getElementById('ticketCount');if(!grid)return;const list=ticketServices.filter(s=>{const text=`${s.name||''} ${s.short||''} ${s.description||''}`.toLowerCase();return (activeTicketType==='ALL'||ticketType(s)===activeTicketType)&&(ticketDestination==='ALL'||ticketLocation(s)===ticketDestination)&&matchesTicketPrice(s)&&(!ticketSearch||text.includes(ticketSearch));});if(count)count.textContent=`${list.length} lựa chọn`;if(!list.length){grid.innerHTML='<div class="ticket-empty">Không có vé phù hợp. Hãy thử thay đổi bộ lọc.</div>';return;}grid.innerHTML=list.map(service=>{const image=ticketImageUrl(service.image);const name=escapeTicketHtml(service.name);return `<article class="ticket-card"><div class="ticket-media">${image?`<img src="${escapeTicketHtml(image)}" alt="${name}" loading="lazy">`:`<span>${ticketIcon(service)}</span>`}<span class="ticket-badge">${escapeTicketHtml(ticketType(service))}</span></div><div class="ticket-body"><div class="ticket-location">📍 ${escapeTicketHtml(ticketLocation(service))}</div><h3>${name}</h3><p>${escapeTicketHtml(service.short)}</p><div class="ticket-card-footer"><div class="ticket-price">Từ<strong>${formatTicketPrice(service.price_from)}</strong></div><a class="btn btn-primary" href="service-detail.html?slug=${encodeURIComponent(service.slug)}">Xem chi tiết</a></div></div></article>`;}).join('');}
document.addEventListener('DOMContentLoaded',loadTickets);
