// ANNLETRAVEL - TICKETS / THINGS TO DO
function escapeTicketHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function ticketImageUrl(value){const url=String(value||'').trim();return /^https:\/\/[^\s"'<>]+$/i.test(url)?url:'';}
function ticketType(service){const id=service.id||'';if(['sun-world','ba-na-hills','fansipan','vinwonders'].includes(id))return 'Công viên & khu vui chơi';if(id==='show-tickets')return 'Show & biểu diễn';if(id==='attraction-tickets')return 'Điểm tham quan';return 'Trải nghiệm';}
function ticketLocation(service){const id=service.id||'';if(id==='ba-na-hills')return 'Đà Nẵng';if(id==='fansipan')return 'Sapa';if(id==='vinwonders')return 'Nhiều điểm đến';if(id==='sun-world')return 'Nhiều điểm đến';return 'Theo điểm đến';}
function ticketIcon(service){const type=ticketType(service);if(type==='Công viên & khu vui chơi')return '🎢';if(type==='Show & biểu diễn')return '🎭';if(type==='Điểm tham quan')return '🏛️';return '✨';}
let ticketServices=[];let activeTicketType='ALL';
async function loadTickets(){const {data,error}=await supabaseClient.from('services').select('*').eq('category_id','tickets').eq('active',true).order('sort_order',{ascending:true});if(error){console.error('Load tickets error:',error);renderTicketError();return;}ticketServices=data||[];renderTicketFilters();renderTickets();}
function renderTicketError(){const grid=document.getElementById('ticketGrid');if(grid)grid.innerHTML='<div class="ticket-empty">Không thể tải danh sách vé. Vui lòng thử lại sau.</div>';}
function renderTicketFilters(){const el=document.getElementById('ticketFilters');if(!el)return;const types=['ALL','Công viên & khu vui chơi','Điểm tham quan','Show & biểu diễn','Trải nghiệm'];el.innerHTML=types.map(type=>`<button class="ticket-filter${activeTicketType===type?' active':''}" data-type="${escapeTicketHtml(type)}">${type==='ALL'?'Tất cả':escapeTicketHtml(type)}</button>`).join('');el.querySelectorAll('.ticket-filter').forEach(btn=>btn.addEventListener('click',()=>{activeTicketType=btn.dataset.type;renderTicketFilters();renderTickets();}));}
function formatTicketPrice(value){const n=Number(value);return Number.isFinite(n)&&n>0?`${new Intl.NumberFormat('vi-VN').format(n)} đ`:'Liên hệ';}
function renderTickets(){const grid=document.getElementById('ticketGrid');const count=document.getElementById('ticketCount');if(!grid)return;const list=activeTicketType==='ALL'?ticketServices:ticketServices.filter(s=>ticketType(s)===activeTicketType);if(count)count.textContent=`${list.length} lựa chọn`;if(!list.length){grid.innerHTML='<div class="ticket-empty">Chưa có vé phù hợp với bộ lọc này.</div>';return;}grid.innerHTML=list.map(service=>{const image=ticketImageUrl(service.image);const name=escapeTicketHtml(service.name);return `<article class="ticket-card"><div class="ticket-media">${image?`<img src="${escapeTicketHtml(image)}" alt="${name}" loading="lazy">`:`<span>${ticketIcon(service)}</span>`}<span class="ticket-badge">${escapeTicketHtml(ticketType(service))}</span></div><div class="ticket-body"><div class="ticket-location">📍 ${escapeTicketHtml(ticketLocation(service))}</div><h3>${name}</h3><p>${escapeTicketHtml(service.short)}</p><div class="ticket-card-footer"><div class="ticket-price">Từ<strong>${formatTicketPrice(service.price_from)}</strong></div><a class="btn btn-primary" href="service-detail.html?slug=${encodeURIComponent(service.slug)}">Xem chi tiết</a></div></div></article>`;}).join('');}
document.addEventListener('DOMContentLoaded',loadTickets);
