let posts=[];let destinations=[];let editingId=null;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}
async function checkAdmin(userId){const {data,error}=await supabaseClient.from('admin_users').select('user_id').eq('user_id',userId).maybeSingle();if(error)console.error(error);return !!data;}
async function init(){const {data:{session}}=await supabaseClient.auth.getSession();if(session&&await checkAdmin(session.user.id)) showDashboard();else showLogin();}
function showLogin(){ $('loginPage').classList.remove('hidden');$('dashboardPage').classList.add('hidden'); }
async function showDashboard(){ $('loginPage').classList.add('hidden');$('dashboardPage').classList.remove('hidden');await loadDestinations();await loadPosts(); }
async function loadDestinations(){const {data,error}=await supabaseClient.from('destinations').select('name,slug').order('sort_order',{ascending:true});if(error){console.error(error);return;}destinations=data||[];$('destination').innerHTML='<option value="">Không gắn điểm đến</option>'+destinations.map(d=>`<option value="${esc(d.name)}">${esc(d.name)}</option>`).join('');}
async function loadPosts(){const {data,error}=await supabaseClient.from('blog_posts').select('*').order('created_at',{ascending:false});if(error){$('postTableBody').innerHTML=`<tr><td colspan="6">Không tải được bài viết. Hãy chạy supabase/blog.sql trước.</td></tr>`;console.error(error);return;}posts=data||[];$('postCount').textContent=`${posts.length} bài viết`;renderPosts();}
function renderPosts(){$('postTableBody').innerHTML=posts.length?posts.map(p=>`<tr><td><div class="blog-admin-title">${esc(p.title)}</div><div class="blog-admin-slug">${esc(p.slug)}</div></td><td>${esc(p.category||'-')}</td><td>${esc(p.destination||'-')}</td><td><span class="blog-status ${p.published?'on':'off'}">${p.published?'Đã xuất bản':'Bản nháp'}</span></td><td>${p.updated_at?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short'}).format(new Date(p.updated_at)):'-'}</td><td><div class="blog-actions"><button class="edit-button" onclick="editPost('${p.id}')">Sửa</button><button class="delete-button" onclick="deletePost('${p.id}')">Xóa</button></div></td></tr>`).join(''):`<tr><td colspan="6">Chưa có bài viết.</td></tr>`;}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function resetForm(){editingId=null;$('postForm').reset();$('postId').value='';$('category').value='Kinh nghiệm du lịch';$('destination').value='';$('coverPreview').style.backgroundImage='';$('editorTitle').textContent='Bài viết mới';}
function openEditor(post=null){$('listView').classList.add('blog-admin-hidden');$('editorView').classList.remove('blog-admin-hidden');resetForm();if(post){editingId=post.id;$('editorTitle').textContent='Sửa bài viết';$('postId').value=post.id;$('title').value=post.title||'';$('slug').value=post.slug||'';$('excerpt').value=post.excerpt||'';$('content').value=post.content||'';$('category').value=post.category||'Kinh nghiệm du lịch';$('destination').value=post.destination||'';$('coverImage').value=post.cover_image||'';$('seoTitle').value=post.seo_title||'';$('seoDescription').value=post.seo_description||'';$('published').checked=!!post.published;updatePreview();}}
window.editPost=id=>{const post=posts.find(p=>p.id===id);if(post)openEditor(post);};
window.deletePost=async id=>{const post=posts.find(p=>p.id===id);if(!post||!confirm(`Xóa bài viết "${post.title}"?`))return;const {error}=await supabaseClient.from('blog_posts').delete().eq('id',id);if(error){alert('Không thể xóa: '+error.message);return;}await loadPosts();};
function updatePreview(){const url=$('coverImage').value.trim();$('coverPreview').style.backgroundImage=url?`url("${url.replace(/"/g,'')} ")`:'';}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';const {data,error}=await supabaseClient.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error||!data.user||!(await checkAdmin(data.user.id))){await supabaseClient.auth.signOut();$('loginError').textContent='Email/mật khẩu không đúng hoặc tài khoản chưa có quyền Admin.';return;}await showDashboard();});
$('logoutButton').addEventListener('click',async()=>{await supabaseClient.auth.signOut();showLogin();});
$('newPostButton').addEventListener('click',()=>openEditor());$('backButton').addEventListener('click',()=>{$('editorView').classList.add('blog-admin-hidden');$('listView').classList.remove('blog-admin-hidden');});$('cancelEdit').addEventListener('click',()=>{$('editorView').classList.add('blog-admin-hidden');$('listView').classList.remove('blog-admin-hidden');});$('refreshButton').addEventListener('click',loadPosts);$('coverImage').addEventListener('input',updatePreview);$('title').addEventListener('blur',()=>{if(!$('slug').value.trim())$('slug').value=slugify($('title').value);if(!$('seoTitle').value.trim())$('seoTitle').value=$('title').value+' | ANNLETRAVEL';});
$('postForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('title').value.trim(),slug=slugify($('slug').value.trim());const payload={title,slug,excerpt:$('excerpt').value.trim(),content:$('content').value,cover_image:$('coverImage').value.trim()||null,seo_title:$('seoTitle').value.trim()||null,seo_description:$('seoDescription').value.trim()||null,category:$('category').value.trim()||'Kinh nghiệm du lịch',destination:$('destination').value||null,published:$('published').checked,published_at:$('published').checked?new Date().toISOString():null,updated_at:new Date().toISOString()};if(!title||!slug||!payload.content){alert('Vui lòng nhập tiêu đề, slug và nội dung.');return;}let result;if(editingId)result=await supabaseClient.from('blog_posts').update(payload).eq('id',editingId);else result=await supabaseClient.from('blog_posts').insert(payload);if(result.error){alert('Không thể lưu bài viết:\n'+result.error.message);return;}alert('Đã lưu bài viết.');$('editorView').classList.add('blog-admin-hidden');$('listView').classList.remove('blog-admin-hidden');await loadPosts();});
init();
